version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  web:
    build: .
    #wait for postgress to start and roll migrations
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: forstream_test
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
