# Generated by Django 2.2.3 on 2019-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date of sending')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
